spring:
  datasource:
    url: jdbc:mysql://localhost:3308/mercadolivroprod?createDatabaseIfNotExist=true
    username: root
    password: pass

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false